// <auto-generated />
using System;
using Furniture_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Furniture_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Furniture_Project.Models.Barang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Harga")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("NamaBarang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stok")
                        .HasColumnType("int");

                    b.Property<int>("Terjual")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tb_Barang");
                });

            modelBuilder.Entity("Furniture_Project.Models.Pemesanan", b =>
                {
                    b.Property<int>("Id_Pesanan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BarangId")
                        .HasColumnType("int");

                    b.Property<int>("Jumlah_Pesan")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tanggal_Pesan")
                        .HasColumnType("datetime");

                    b.Property<double>("Total_pesan")
                        .HasColumnType("double");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id_Pesanan");

                    b.HasIndex("BarangId");

                    b.HasIndex("UserName");

                    b.ToTable("Tb_Pemesanan");
                });

            modelBuilder.Entity("Furniture_Project.Models.Roles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tb_Roles");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Furniture_Project.Models.User", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RolesId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.HasIndex("RolesId");

                    b.ToTable("Tb_User");
                });

            modelBuilder.Entity("Furniture_Project.Models.Pemesanan", b =>
                {
                    b.HasOne("Furniture_Project.Models.Barang", "Barang")
                        .WithMany()
                        .HasForeignKey("BarangId");

                    b.HasOne("Furniture_Project.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserName");

                    b.Navigation("Barang");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Furniture_Project.Models.User", b =>
                {
                    b.HasOne("Furniture_Project.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
